# AI Models configuration
[ai.models]
chat_model = "ollama/gpt-oss:20b"
edit_model = "ollama/gpt-oss:20b"
autocomplete_model = "ollama/gpt-oss:20b"

# Ollama configuration
[ai.ollama]
base_url = "http://10.0.8.190:11434/v1"
